// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RolodexWinformEFC.Models;

namespace RolodexWinformEFC.Migrations
{
    [DbContext(typeof(RolodexContext))]
    [Migration("20200414195635_added contact info")]
    partial class addedcontactinfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("RolodexWinformEFC.Models.RolodexContact", b =>
                {
                    b.Property<int>("RolodexContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HowToContact")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerRolodexEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolodexContactId");

                    b.HasIndex("OwnerRolodexEntryId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("RolodexWinformEFC.Models.RolodexEntry", b =>
                {
                    b.Property<int>("RolodexEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNameMI")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("RolodexEntryId");

                    b.ToTable("Rolodex");
                });

            modelBuilder.Entity("RolodexWinformEFC.Models.RolodexContact", b =>
                {
                    b.HasOne("RolodexWinformEFC.Models.RolodexEntry", "Owner")
                        .WithMany("ContactInfo")
                        .HasForeignKey("OwnerRolodexEntryId");
                });
#pragma warning restore 612, 618
        }
    }
}
