// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RolodexWinformEFC.Models;

namespace RolodexWinformEFC.Migrations
{
    [DbContext(typeof(RolodexContext))]
    [Migration("20200414162251_covid")]
    partial class covid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("RolodexWinformEFC.Models.RolodexEntry", b =>
                {
                    b.Property<int>("RolodexEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AdmitDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstNameMI")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MRN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SSN")
                        .HasColumnType("TEXT");

                    b.HasKey("RolodexEntryId");

                    b.ToTable("Rolodex");
                });
#pragma warning restore 612, 618
        }
    }
}
